# Generated by Django 5.2.10 on 2026-02-12 15:38
# Cleaned up: seed data functions inlined, no-op data migrations removed.

import battycoda_app.models.organization
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


# ---------------------------------------------------------------------------
# Seed-data functions (copied from 0002 and 0012, made idempotent)
# ---------------------------------------------------------------------------

def create_default_segmentation_algorithms(apps, schema_editor):
    SegmentationAlgorithm = apps.get_model("battycoda_app", "SegmentationAlgorithm")

    SegmentationAlgorithm.objects.get_or_create(
        name="Threshold-based Detector",
        defaults=dict(
            description="Detects calls by taking the absolute value of the audio signal, smoothing it, and applying a threshold based on signal statistics.",
            algorithm_type="threshold",
            celery_task="battycoda_app.audio.task_modules.segmentation_tasks.auto_segment_recording_task",
            is_active=True,
            default_min_duration_ms=10,
            default_smooth_window=3,
            default_threshold_factor=0.5,
        ),
    )

    SegmentationAlgorithm.objects.get_or_create(
        name="Energy-based Detector",
        defaults=dict(
            description="Analyzes the short-time energy of the signal to detect calls, with better performance in noisy recordings.",
            algorithm_type="energy",
            celery_task="battycoda_app.audio.task_modules.segmentation_tasks.auto_segment_recording_task",
            is_active=True,
            default_min_duration_ms=8,
            default_smooth_window=5,
            default_threshold_factor=0.4,
        ),
    )


def create_system_species(apps, schema_editor):
    Species = apps.get_model("battycoda_app", "Species")
    Call = apps.get_model("battycoda_app", "Call")

    # Eptesicus fuscus
    efuscus, _ = Species.objects.get_or_create(
        name="Eptesicus fuscus",
        is_system=True,
        defaults=dict(
            description="Eptesicus fuscus (big brown bat) is a species found across North America.",
            created_by=None,
            group=None,
        ),
    )
    efuscus_calls = [
        ("LsDFM-LFM", "long shallow frequency modulation downward—long frequency modulation"),
        ("LFM", "long frequency modulation"),
        ("Echo", "echolocation call"),
        ("LQCF-CS", "long quasi-constant frequency to chevron shape"),
        ("U", "U-shaped call"),
        ("LDFM", "long downward frequency modulation long"),
        ("sHFM", "single humped frequency modulation"),
        ("QCF", "quasi-constant frequency"),
        ("QFC-DFM", "quasi-constant frequency to downward frequency modulation"),
        ("UFM", "upward frequency modulation"),
        ("CS", "chevron shaped call"),
        ("DFM", "downward frequency modulation"),
        ("FMB", "frequency modulated bout"),
        ("U-LDFM", "U-shaped call long downward frequency modulation long"),
        ("SFM", "short frequency modulation"),
    ]
    for short_name, long_name in efuscus_calls:
        Call.objects.get_or_create(species=efuscus, short_name=short_name, defaults=dict(long_name=long_name))

    # Carollia perspicillata
    carollia, _ = Species.objects.get_or_create(
        name="Carollia perspicillata",
        is_system=True,
        defaults=dict(
            description="Carollia perspicillata (short-tailed leaf-nosed bat) is a fruit-eating bat found in Central and South America.",
            created_by=None,
            group=None,
        ),
    )
    carollia_calls = [
        ("aggressive down-sweeps (A)", ""),
        ("aggressive warbles", ""),
        ("male aggressive trills", ""),
        ("distress calls", ""),
        ("benign wobbles", ""),
        ("male courtship trills", ""),
        ("pup isolation calls", ""),
        ("echolocation calls", ""),
        ("V-shaped calls", ""),
        ("flat down-sweeps", ""),
        ("hooks", ""),
        ("noise", ""),
    ]
    for short_name, long_name in carollia_calls:
        Call.objects.get_or_create(species=carollia, short_name=short_name, defaults=dict(long_name=long_name))


def create_default_classifiers(apps, schema_editor):
    Classifier = apps.get_model("battycoda_app", "Classifier")
    Species = apps.get_model("battycoda_app", "Species")

    efuscus = Species.objects.filter(name="Eptesicus fuscus").first()
    carollia = Species.objects.filter(name="Carollia perspicillata").first()

    classifiers = [
        dict(
            name="KNN E. fuscus",
            description="K-Nearest Neighbors classifier for Eptesicus fuscus bat calls.",
            response_format="full_probability",
            celery_task="battycoda_app.audio.task_modules.classification_tasks.run_call_detection",
            service_url="http://localhost:8000",
            endpoint="/predict/knn",
            model_file="data/models/efuscus_knn_model.RData",
            species=efuscus,
            is_active=True,
        ),
        dict(
            name="LDA E. fuscus",
            description="Linear Discriminant Analysis classifier for Eptesicus fuscus bat calls.",
            response_format="full_probability",
            celery_task="battycoda_app.audio.task_modules.classification_tasks.run_call_detection",
            service_url="http://localhost:8000",
            endpoint="/predict/lda",
            model_file="data/models/efuscus_lda_model.RData",
            species=efuscus,
            is_active=True,
        ),
        dict(
            name="KNN Carollia",
            description="K-Nearest Neighbors classifier for Carollia perspicillata bat calls.",
            response_format="full_probability",
            celery_task="battycoda_app.audio.task_modules.classification_tasks.run_call_detection",
            service_url="http://localhost:8000",
            endpoint="/predict/knn",
            model_file="data/models/carollia_knn_model.RData",
            species=carollia,
            is_active=True,
        ),
        dict(
            name="LDA Carollia",
            description="Linear Discriminant Analysis classifier for Carollia perspicillata bat calls.",
            response_format="full_probability",
            celery_task="battycoda_app.audio.task_modules.classification_tasks.run_call_detection",
            service_url="http://localhost:8000",
            endpoint="/predict/lda",
            model_file="data/models/carollia_lda_model.RData",
            species=carollia,
            is_active=True,
        ),
        dict(
            name="Dummy Classifier",
            description="A simple classifier that assigns equal probability to all call types.",
            response_format="full_probability",
            celery_task="battycoda_app.audio.task_modules.detection_tasks.run_dummy_classifier",
            is_active=True,
        ),
    ]
    for c in classifiers:
        Classifier.objects.get_or_create(name=c.pop("name"), defaults=c)


def create_rousettus_aegyptiacus_species(apps, schema_editor):
    Species = apps.get_model("battycoda_app", "Species")
    Call = apps.get_model("battycoda_app", "Call")

    rousettus, _ = Species.objects.get_or_create(
        name="Rousettus aegyptiacus",
        is_system=True,
        defaults=dict(
            description="Rousettus aegyptiacus (Egyptian fruit bat) is a megabat species found in Africa and the Middle East.",
            created_by=None,
            group=None,
        ),
    )
    rousettus_calls = [
        ("Tr", "Trill"),
        ("Ba", "Bark"),
        ("Pi", "Pitchy Call"),
        ("LPi", "Loud Pitchy Call"),
        ("Bu", "Low Buzz"),
        ("Pa", "Panting"),
        ("LT", "Low Tuck"),
        ("Sq", "Squeal"),
        ("Ra", "Rattle"),
        ("Ch", "Chuckles"),
        ("BB", "Bark Buzz"),
        ("PB", "Pitchy Call Buzz"),
        ("SB", "Squeal Buzz"),
        ("Un", "Unknown"),
    ]
    for short_name, long_name in rousettus_calls:
        Call.objects.get_or_create(species=rousettus, short_name=short_name, defaults=dict(long_name=long_name))


# ---------------------------------------------------------------------------
# Migration class
# ---------------------------------------------------------------------------

class Migration(migrations.Migration):

    replaces = [('battycoda_app', '0001_initial'), ('battycoda_app', '0002_initial_data_setup'), ('battycoda_app', '0003_alter_taskbatch_unique_together_and_more'), ('battycoda_app', '0004_add_file_ready_flag'), ('battycoda_app', '0005_add_clustering_models'), ('battycoda_app', '0006_remove_is_admin_cache'), ('battycoda_app', '0007_add_spectrogram_job_model'), ('battycoda_app', '0008_task_annotated_at_task_annotated_by'), ('battycoda_app', '0009_add_features_file_to_detection_run'), ('battycoda_app', '0010_add_api_key_to_userprofile'), ('battycoda_app', '0011_add_queued_status_to_detection_run'), ('battycoda_app', '0012_add_rousettus_aegyptiacus'), ('battycoda_app', '0013_auto_20250706_2109'), ('battycoda_app', '0014_auto_20250716_1838'), ('battycoda_app', '0015_auto_20250717_2356'), ('battycoda_app', '0016_add_last_activity_field'), ('battycoda_app', '0017_add_management_features_flag'), ('battycoda_app', '0018_resolve_migration_conflicts'), ('battycoda_app', '0019_auto_20250916_0117'), ('battycoda_app', '0020_rename_detection_run_to_classification_run'), ('battycoda_app', '0021_add_spectrogram_file_to_recording'), ('battycoda_app', '0022_add_hidden_to_recording'), ('battycoda_app', '0021_remove_segmentation_is_active'), ('battycoda_app', '0023_merge_remove_is_active_add_hidden'), ('battycoda_app', '0024_rename_detection_result_callprobability_classification_result_and_more'), ('battycoda_app', '0025_species_detail_padding_end_ms_and_more'), ('battycoda_app', '0026_task_status_and_progress_tracking'), ('battycoda_app', '0027_make_task_batch_nullable_in_training_job'), ('battycoda_app', '0028_project_level_clustering'), ('battycoda_app', '0029_simplify_themes'), ('battycoda_app', '0030_alter_call_long_name_and_more'), ('battycoda_app', '0031_recording_processing_status'), ('battycoda_app', '0032_change_min_duration_to_float'), ('battycoda_app', '0033_tus_upload')]

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # ---------------------------------------------------------------
        # Schema: all tables in their final form
        # ---------------------------------------------------------------
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=50)),
                ('long_name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['short_name'],
            },
        ),
        migrations.CreateModel(
            name='Classifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the classification algorithm', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Description of how the algorithm works')),
                ('response_format', models.CharField(choices=[('full_probability', 'Full Probability Distribution'), ('highest_only', 'Highest Probability Only')], help_text='Format of the response returned by this algorithm', max_length=20)),
                ('celery_task', models.CharField(default='battycoda_app.audio.task_modules.classification_tasks.run_classification', help_text='Fully qualified Celery task name to execute this algorithm', max_length=255)),
                ('service_url', models.CharField(blank=True, default='', help_text='URL of the external service, if applicable', max_length=255)),
                ('endpoint', models.CharField(blank=True, default='', help_text='Endpoint path for the service', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this classifier is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_file', models.CharField(blank=True, default='', help_text='Path to the model file for custom trained classifiers', max_length=512)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this classifier', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_classifiers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClassificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['segment__onset'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CallProbability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability', models.FloatField(help_text='Probability value between 0-1')),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='probabilities', to='battycoda_app.call')),
                ('classification_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='probabilities', to='battycoda_app.classificationresult')),
            ],
            options={
                'ordering': ['-probability'],
            },
        ),
        migrations.CreateModel(
            name='ClassificationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('algorithm_type', models.CharField(choices=[('full_probability', 'Full Probability Distribution'), ('highest_only', 'Highest Probability Only')], default='highest_only', help_text='Whether the algorithm returns full probability distributions or only the highest probability', max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress', models.FloatField(default=0.0, help_text='Progress percentage from 0-100')),
                ('error_message', models.TextField(blank=True, default='')),
                ('features_file', models.CharField(blank=True, default='', help_text='Path to the exported features CSV file', max_length=512)),
                ('classifier', models.ForeignKey(blank=True, help_text='The classifier algorithm used for this classification run', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classification_runs', to='battycoda_app.classifier')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification_runs', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classification_runs', to='battycoda_app.group')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='classificationresult',
            name='classification_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='battycoda_app.classificationrun'),
        ),
        migrations.AddField(
            model_name='classifier',
            name='group',
            field=models.ForeignKey(blank=True, help_text="Group that owns this classifier. If null, it's available to all groups", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classifiers', to='battycoda_app.group'),
        ),
        migrations.CreateModel(
            name='GroupInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(help_text='Unique token for invitation link', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='battycoda_app.group')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoginCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_codes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='battycoda_app.group')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'group')},
            },
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the recording', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Description of the recording')),
                ('wav_file', models.FileField(help_text='WAV file for the recording', upload_to='recordings/')),
                ('duration', models.FloatField(blank=True, help_text='Duration of the recording in seconds', null=True)),
                ('sample_rate', models.IntegerField(blank=True, help_text='Sample rate of the recording in Hz', null=True)),
                ('recorded_date', models.DateField(blank=True, help_text='Date when the recording was made', null=True)),
                ('location', models.CharField(blank=True, default='', help_text='Location where the recording was made', max_length=255)),
                ('equipment', models.CharField(blank=True, default='', help_text='Equipment used for recording', max_length=255)),
                ('environmental_conditions', models.TextField(blank=True, default='', help_text='Environmental conditions during recording')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_ready', models.BooleanField(default=False, help_text='Flag indicating if the file is fully uploaded and ready for processing')),
                ('spectrogram_file', models.CharField(blank=True, default='', help_text='Filename of the generated spectrogram PNG', max_length=255)),
                ('hidden', models.BooleanField(default=False, help_text="Hidden recordings are temporary previews that don't appear in normal lists")),
                ('processing_status', models.CharField(choices=[('processing', 'Processing'), ('ready', 'Ready')], default='processing', help_text="Processing status: 'processing' while spectrogram is being generated, 'ready' when complete", max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(help_text='Group that owns this recording', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='battycoda_app.group')),
                ('project', models.ForeignKey(help_text='Project this recording belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='battycoda_app.project')),
            ],
            options={
                'verbose_name': 'Recording',
                'verbose_name_plural': 'Recordings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', help_text='Optional name for this segment', max_length=255)),
                ('onset', models.FloatField(help_text='Start time of the segment in seconds')),
                ('offset', models.FloatField(help_text='End time of the segment in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Notes about this segment')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to=settings.AUTH_USER_MODEL)),
                ('recording', models.ForeignKey(help_text='Recording this segment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='battycoda_app.recording')),
            ],
            options={
                'ordering': ['onset'],
            },
        ),
        migrations.AddField(
            model_name='classificationresult',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification_results', to='battycoda_app.segment'),
        ),
        migrations.CreateModel(
            name='Segmentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Segmentation', help_text='Descriptive name for this segmentation run', max_length=255)),
                ('task_id', models.CharField(blank=True, default='', help_text='Celery task ID for automated segmentation', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20)),
                ('progress', models.FloatField(default=100, help_text='Progress percentage (0-100)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('min_duration_ms', models.FloatField(default=10)),
                ('smooth_window', models.IntegerField(default=3)),
                ('threshold_factor', models.FloatField(default=0.5)),
                ('segments_created', models.IntegerField(default=0)),
                ('manually_edited', models.BooleanField(default=False, help_text='Indicates if this segmentation was manually edited after initial creation')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recording', models.ForeignKey(help_text='The recording this segmentation belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='segmentations', to='battycoda_app.recording')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='segment',
            name='segmentation',
            field=models.ForeignKey(help_text='Segmentation that manages this segment', on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='battycoda_app.segmentation'),
        ),
        migrations.AddField(
            model_name='classificationrun',
            name='segmentation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification_runs', to='battycoda_app.segmentation'),
        ),
        migrations.CreateModel(
            name='SegmentationAlgorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the segmentation algorithm', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Description of how the algorithm works')),
                ('algorithm_type', models.CharField(choices=[('threshold', 'Threshold-based Detection'), ('energy', 'Energy-based Detection'), ('ml', 'Machine Learning Detection'), ('external', 'External Service')], default='threshold', help_text='Type of segmentation algorithm', max_length=20)),
                ('celery_task', models.CharField(default='battycoda_app.audio.task_modules.segmentation_tasks.auto_segment_recording_task', help_text='Fully qualified Celery task name to execute this algorithm', max_length=255)),
                ('service_url', models.CharField(blank=True, default='', help_text='URL of the external service, if applicable', max_length=255)),
                ('endpoint', models.CharField(blank=True, default='', help_text='Endpoint path for the service', max_length=255)),
                ('default_min_duration_ms', models.FloatField(default=10, help_text='Default minimum duration in milliseconds')),
                ('default_smooth_window', models.IntegerField(default=3, help_text='Default smoothing window size')),
                ('default_threshold_factor', models.FloatField(default=0.5, help_text='Default threshold factor (0-10)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this algorithm is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, help_text="Group that owns this algorithm. If null, it's available to all groups", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segmentation_algorithms', to='battycoda_app.group')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='segmentation',
            name='algorithm',
            field=models.ForeignKey(blank=True, help_text='The algorithm used for this segmentation, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segmentations', to='battycoda_app.segmentationalgorithm'),
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to=battycoda_app.models.organization.get_species_image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_system', models.BooleanField(default=False, help_text='Designates whether this is a system-wide species available to all users')),
                ('detail_padding_end_ms', models.IntegerField(default=8, help_text='Padding in milliseconds after the call in detail view spectrograms')),
                ('detail_padding_start_ms', models.IntegerField(default=8, help_text='Padding in milliseconds before the call in detail view spectrograms')),
                ('overview_padding_end_ms', models.IntegerField(default=500, help_text='Padding in milliseconds after the call in overview spectrograms')),
                ('overview_padding_start_ms', models.IntegerField(default=500, help_text='Padding in milliseconds before the call in overview spectrograms')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='species', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='species', to='battycoda_app.group')),
            ],
            options={
                'verbose_name_plural': 'Species',
                'ordering': ['name'],
                'unique_together': {('name', 'group')},
            },
        ),
        migrations.AddField(
            model_name='recording',
            name='species',
            field=models.ForeignKey(help_text='Species associated with this recording', on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='battycoda_app.species'),
        ),
        migrations.AddField(
            model_name='call',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='battycoda_app.species'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wav_file_name', models.CharField(max_length=255)),
                ('onset', models.FloatField(help_text='Start time of the segment in seconds')),
                ('offset', models.FloatField(help_text='End time of the segment in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('done', 'Done')], default='pending', max_length=20)),
                ('is_done', models.BooleanField(default=False, help_text='Indicates that the task has been fully reviewed and labeled')),
                ('classification_result', models.CharField(blank=True, default='', max_length=100)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('label', models.CharField(blank=True, default='', help_text='Final expert label assigned to this task', max_length=255)),
                ('notes', models.TextField(blank=True, default='', help_text='Additional notes or observations about this task')),
                ('annotated_at', models.DateTimeField(blank=True, help_text='When the annotation was completed', null=True)),
                ('in_progress_by', models.ForeignKey(blank=True, help_text='User currently working on this task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_in_progress', to=settings.AUTH_USER_MODEL)),
                ('in_progress_since', models.DateTimeField(blank=True, help_text='When the user started working on this task', null=True)),
                ('annotated_by', models.ForeignKey(blank=True, help_text='User who provided the annotation/label', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotated_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='battycoda_app.group')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='battycoda_app.project')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='battycoda_app.species')),
                ('source_segment', models.ForeignKey(blank=True, help_text='The segment this task was created from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='battycoda_app.segment')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wav_file_name', models.CharField(max_length=255)),
                ('wav_file', models.FileField(blank=True, null=True, upload_to='task_batches/')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_batches', to=settings.AUTH_USER_MODEL)),
                ('classification_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_batches', to='battycoda_app.classificationrun')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_batches', to='battycoda_app.group')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_batches', to='battycoda_app.project')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_batches', to='battycoda_app.species')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='battycoda_app.taskbatch'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', help_text='Color theme preference', max_length=20)),
                ('cloudflare_id', models.CharField(blank=True, default='', help_text='Deprecated - kept for data compatibility', max_length=255)),
                ('is_cloudflare_user', models.BooleanField(default=False, help_text='Deprecated - kept for data compatibility')),
                ('cloudflare_email', models.EmailField(blank=True, default='', help_text='Deprecated - kept for data compatibility', max_length=254)),
                ('last_cloudflare_login', models.DateTimeField(blank=True, help_text='Deprecated - kept for data compatibility', null=True)),
                ('profile_image', models.ImageField(blank=True, help_text='Profile image', null=True, upload_to='profile_images/')),
                ('api_key', models.CharField(blank=True, help_text='API key for programmatic access', max_length=40, null=True, unique=True)),
                ('last_activity', models.DateTimeField(blank=True, help_text='Last time the user performed any significant action', null=True)),
                ('management_features_enabled', models.BooleanField(default=False, help_text='Enable access to management and administrative features')),
                ('group', models.ForeignKey(help_text='Every user must belong to a group', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='battycoda_app.group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='battycoda_app.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'group')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='call',
            unique_together={('species', 'short_name')},
        ),
        migrations.AddField(
            model_name='classifier',
            name='species',
            field=models.ForeignKey(blank=True, help_text='Species this classifier is trained for. Once set, this cannot be changed.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classifiers', to='battycoda_app.species'),
        ),
        migrations.AddField(
            model_name='classifier',
            name='source_task_batch',
            field=models.ForeignKey(blank=True, help_text='The task batch that was used to train this classifier', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_classifiers', to='battycoda_app.taskbatch'),
        ),
        migrations.CreateModel(
            name='ClassifierTrainingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name for this training job', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Description of the training job')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('response_format', models.CharField(choices=[('full_probability', 'Full Probability Distribution'), ('highest_only', 'Highest Probability Only')], default='highest_only', help_text='Format of the response returned by this classifier', max_length=20)),
                ('parameters', models.JSONField(blank=True, help_text='JSON with training parameters', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress', models.FloatField(default=0.0, help_text='Progress percentage from 0-100')),
                ('error_message', models.TextField(blank=True, default='')),
                ('classifier', models.ForeignKey(blank=True, help_text='The classifier created by this training job (set after successful completion)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_job', to='battycoda_app.classifier')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_jobs', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_jobs', to='battycoda_app.group')),
                ('task_batch', models.ForeignKey(blank=True, help_text='The task batch used for training this classifier (null if trained from folder)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_jobs', to='battycoda_app.taskbatch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the notification', max_length=255)),
                ('message', models.TextField(help_text='Notification message content')),
                ('notification_type', models.CharField(choices=[('segmentation', 'Segmentation Notification'), ('classification', 'Classification Notification'), ('training', 'Classifier Training Notification'), ('system', 'System Notification'), ('info', 'Information')], default='info', help_text='Type of notification', max_length=20)),
                ('icon', models.CharField(choices=[('s7-check', 'Success'), ('s7-close', 'Error'), ('s7-info', 'Info'), ('s7-attention', 'Warning'), ('s7-bell', 'Notification')], default='s7-bell', help_text='Icon to display with notification', max_length=20)),
                ('link', models.CharField(blank=True, default='', help_text='Optional link to view related content', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False, help_text='Whether the notification has been read')),
                ('user', models.ForeignKey(help_text='User who will receive this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClusteringAlgorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the clustering algorithm', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Description of how the algorithm works')),
                ('algorithm_type', models.CharField(choices=[('kmeans', 'K-Means Clustering'), ('dbscan', 'DBSCAN Density-Based Clustering'), ('hierarchical', 'Hierarchical Clustering'), ('gaussian_mixture', 'Gaussian Mixture Model'), ('spectral', 'Spectral Clustering'), ('custom', 'Custom Algorithm')], help_text='Type of clustering algorithm to use', max_length=50)),
                ('parameters', models.JSONField(blank=True, help_text="JSON with algorithm parameters (e.g., {'n_clusters': 5, 'random_state': 42})", null=True)),
                ('celery_task', models.CharField(default='battycoda_app.audio.task_modules.clustering_tasks.run_clustering', help_text='Fully qualified Celery task name to execute this algorithm', max_length=255)),
                ('service_url', models.CharField(blank=True, default='', help_text='URL of the external service, if applicable', max_length=255)),
                ('endpoint', models.CharField(blank=True, default='', help_text='Endpoint path for the service', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this algorithm is currently active')),
                ('created_by', models.ForeignKey(help_text='User who created this algorithm', on_delete=django.db.models.deletion.CASCADE, related_name='created_clustering_algorithms', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, help_text="Group that owns this algorithm. If null, it's available to all groups", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clustering_algorithms', to='battycoda_app.group')),
            ],
            options={
                'verbose_name': 'Clustering Algorithm',
                'verbose_name_plural': 'Clustering Algorithms',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClusteringRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name for this clustering run', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Description of this clustering run')),
                ('runtime_parameters', models.JSONField(blank=True, help_text='JSON with runtime parameters that override algorithm defaults', null=True)),
                ('n_clusters', models.IntegerField(blank=True, help_text='Number of clusters to create (for algorithms that need this specified)', null=True)),
                ('feature_extraction_method', models.CharField(default='mfcc', help_text='Method used to extract features from audio (e.g., mfcc, spectrogram)', max_length=100)),
                ('feature_parameters', models.JSONField(blank=True, help_text='JSON with parameters for feature extraction', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Current status of the clustering run', max_length=20)),
                ('progress', models.FloatField(default=0.0, help_text='Progress percentage from 0-100')),
                ('error_message', models.TextField(blank=True, default='', help_text='Error message if the run failed')),
                ('task_id', models.CharField(blank=True, default='', help_text='Celery task ID for this clustering run', max_length=100)),
                ('num_segments_processed', models.IntegerField(default=0, help_text='Number of segments processed in this run')),
                ('num_clusters_created', models.IntegerField(default=0, help_text='Number of clusters created in this run')),
                ('silhouette_score', models.FloatField(blank=True, help_text='Silhouette score for clustering quality (-1 to 1, higher is better)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_size', models.IntegerField(default=500, help_text='Number of segments to process per batch for memory management')),
                ('progress_message', models.CharField(blank=True, default='', help_text='Detailed progress message for UI feedback', max_length=255)),
                ('scope', models.CharField(choices=[('segmentation', 'Single Segmentation'), ('project', 'Entire Project')], default='segmentation', help_text='Whether clustering is for a single segmentation or entire project', max_length=20)),
                ('algorithm', models.ForeignKey(help_text='The clustering algorithm used for this run', on_delete=django.db.models.deletion.CASCADE, related_name='clustering_runs', to='battycoda_app.clusteringalgorithm')),
                ('created_by', models.ForeignKey(help_text='User who created this clustering run', on_delete=django.db.models.deletion.CASCADE, related_name='clustering_runs', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(help_text='Group that owns this clustering run', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clustering_runs', to='battycoda_app.group')),
                ('segmentation', models.ForeignKey(blank=True, help_text='The segmentation containing segments to cluster (single-file mode)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clustering_runs', to='battycoda_app.segmentation')),
                ('project', models.ForeignKey(blank=True, help_text='The project containing recordings to cluster (project-wide mode)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clustering_runs', to='battycoda_app.project')),
                ('species', models.ForeignKey(blank=True, help_text='Species to include (required for project-level clustering)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clustering_runs', to='battycoda_app.species')),
            ],
            options={
                'verbose_name': 'Clustering Run',
                'verbose_name_plural': 'Clustering Runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_id', models.IntegerField(help_text='Internal numeric ID of the cluster (0, 1, 2...)')),
                ('label', models.CharField(blank=True, default='', help_text='Expert-assigned label for this cluster', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Description of the acoustic pattern in this cluster')),
                ('is_labeled', models.BooleanField(default=False, help_text='Whether an expert has assigned a label to this cluster')),
                ('size', models.IntegerField(default=0, help_text='Number of segments in this cluster')),
                ('coherence', models.FloatField(blank=True, help_text='Measure of cluster coherence (higher is more coherent)', null=True)),
                ('vis_x', models.FloatField(blank=True, help_text='X-coordinate for 2D visualization', null=True)),
                ('vis_y', models.FloatField(blank=True, help_text='Y-coordinate for 2D visualization', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clustering_run', models.ForeignKey(help_text='The clustering run that created this cluster', on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='battycoda_app.clusteringrun')),
                ('representative_segment', models.ForeignKey(blank=True, help_text='Segment that best represents this cluster', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='representing_clusters', to='battycoda_app.segment')),
            ],
            options={
                'verbose_name': 'Cluster',
                'verbose_name_plural': 'Clusters',
                'ordering': ['clustering_run', 'cluster_id'],
                'unique_together': {('clustering_run', 'cluster_id')},
            },
        ),
        migrations.CreateModel(
            name='ClusterCallMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField(help_text='Confidence score (0-1) for the mapping between cluster and call type')),
                ('notes', models.TextField(blank=True, default='', help_text='Notes about this mapping')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('call', models.ForeignKey(help_text='The call type this cluster is mapped to', on_delete=django.db.models.deletion.CASCADE, related_name='cluster_mappings', to='battycoda_app.call')),
                ('cluster', models.ForeignKey(help_text='The cluster being mapped to a call type', on_delete=django.db.models.deletion.CASCADE, related_name='call_mappings', to='battycoda_app.cluster')),
                ('created_by', models.ForeignKey(help_text='User who created this mapping', on_delete=django.db.models.deletion.CASCADE, related_name='cluster_mappings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cluster-Call Mapping',
                'verbose_name_plural': 'Cluster-Call Mappings',
                'ordering': ['-confidence'],
                'unique_together': {('cluster', 'call')},
            },
        ),
        migrations.CreateModel(
            name='SegmentCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField(default=1.0, help_text="Confidence score (0-1) for this segment's membership in the cluster")),
                ('distance_to_center', models.FloatField(blank=True, help_text='Distance of this segment to the cluster center', null=True)),
                ('cluster', models.ForeignKey(help_text='The cluster this segment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='battycoda_app.cluster')),
                ('segment', models.ForeignKey(help_text='The segment that belongs to a cluster', on_delete=django.db.models.deletion.CASCADE, related_name='segment_clusters', to='battycoda_app.segment')),
            ],
            options={
                'verbose_name': 'Segment Cluster Membership',
                'verbose_name_plural': 'Segment Cluster Memberships',
                'ordering': ['-confidence'],
                'unique_together': {('segment', 'cluster')},
            },
        ),
        migrations.CreateModel(
            name='SpectrogramJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name for the spectrogram job', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the spectrogram generation job', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, default='', help_text='Celery task ID for tracking the background job', max_length=255)),
                ('progress', models.IntegerField(default=0, help_text='Progress percentage (0-100)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('output_file_path', models.CharField(blank=True, default='', help_text='Path to the generated spectrogram file', max_length=500)),
                ('output_file_url', models.CharField(blank=True, default='', help_text='URL to access the generated spectrogram', max_length=500)),
                ('error_message', models.TextField(blank=True, default='', help_text='Error message if the job failed')),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Spectrogram generation parameters (sample rate, window size, etc.)')),
                ('created_by', models.ForeignKey(help_text='User who created this job', on_delete=django.db.models.deletion.CASCADE, related_name='spectrogram_jobs', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(help_text='Group this job belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='spectrogram_jobs', to='battycoda_app.group')),
                ('recording', models.ForeignKey(help_text='Recording to generate spectrogram for', on_delete=django.db.models.deletion.CASCADE, related_name='spectrogram_jobs', to='battycoda_app.recording')),
            ],
            options={
                'verbose_name': 'Spectrogram Job',
                'verbose_name_plural': 'Spectrogram Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClusteringRunSegmentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segments_count', models.IntegerField(default=0, help_text='Number of segments from this segmentation included in the run')),
                ('status', models.CharField(choices=[('included', 'Included'), ('skipped', 'Skipped')], default='included', help_text='Whether this segmentation was included or skipped', max_length=20)),
                ('clustering_run', models.ForeignKey(help_text='The clustering run this segmentation was included in', on_delete=django.db.models.deletion.CASCADE, related_name='included_segmentations', to='battycoda_app.clusteringrun')),
                ('segmentation', models.ForeignKey(help_text='The segmentation included in the clustering run', on_delete=django.db.models.deletion.CASCADE, related_name='included_in_clustering_runs', to='battycoda_app.segmentation')),
            ],
            options={
                'verbose_name': 'Clustering Run Segmentation',
                'verbose_name_plural': 'Clustering Run Segmentations',
                'unique_together': {('clustering_run', 'segmentation')},
            },
        ),
        migrations.CreateModel(
            name='TusUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('upload_length', models.BigIntegerField(help_text='Total file size in bytes declared by client')),
                ('upload_offset', models.BigIntegerField(default=0, help_text='Bytes received so far')),
                ('temp_file_path', models.CharField(help_text='Path to temporary file accumulating chunks', max_length=512)),
                ('filename', models.CharField(help_text='Original filename from Upload-Metadata', max_length=255)),
                ('content_type', models.CharField(default='application/octet-stream', max_length=100)),
                ('metadata_json', models.JSONField(blank=True, default=dict, help_text='Recording metadata (species_id, project_id, name, etc.)')),
                ('is_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tus_uploads', to='battycoda_app.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tus_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        # ---------------------------------------------------------------
        # Seed data
        # ---------------------------------------------------------------
        migrations.RunPython(
            code=create_default_segmentation_algorithms,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            code=create_system_species,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            code=create_default_classifiers,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            code=create_rousettus_aegyptiacus_species,
            reverse_code=migrations.RunPython.noop,
        ),
        # ---------------------------------------------------------------
        # Unique email constraint on auth_user (guarded for fresh DBs)
        # ---------------------------------------------------------------
        migrations.RunSQL(
            sql="ALTER TABLE auth_user ADD CONSTRAINT unique_email UNIQUE (email);",
            reverse_sql="ALTER TABLE auth_user DROP CONSTRAINT IF EXISTS unique_email;",
        ),
    ]
