# Generated by Django 5.2.10 on 2026-04-06 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battycoda_app', '0001_squashed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='spectrogram_colormap',
            field=models.CharField(choices=[('roseus', 'Roseus (default)'), ('classic', 'Classic (black-green-yellow-red)'), ('viridis', 'Viridis'), ('magma', 'Magma'), ('inferno', 'Inferno'), ('plasma', 'Plasma'), ('cividis', 'Cividis'), ('hot', 'Hot'), ('gray', 'Grayscale')], default='roseus', help_text='Colormap for spectrogram display', max_length=20),
        ),
    ]
