# Generated by Django 5.1.7 on 2025-04-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("battycoda_app", "0002_initial_data_setup"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="taskbatch",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="usernotification",
            name="icon",
            field=models.CharField(
                choices=[
                    ("s7-check", "Success"),
                    ("s7-close", "Error"),
                    ("s7-info", "Info"),
                    ("s7-attention", "Warning"),
                    ("s7-bell", "Notification"),
                ],
                default="s7-bell",
                help_text="Icon to display with notification",
                max_length=20,
            ),
        ),
    ]
