# Generated by Django 5.1.7 on 2025-04-13 01:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("battycoda_app", "0003_alter_taskbatch_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recording",
            name="file_ready",
            field=models.BooleanField(
                default=False, help_text="Flag indicating if the file is fully uploaded and ready for processing"
            ),
        ),
    ]
