# Generated by Django 5.1.7 on 2025-03-31 19:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("battycoda_app", "0005_change_default_theme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="theme",
            field=models.CharField(
                choices=[
                    ("default", "Default Green"),
                    ("blue-sky", "Blue Sky"),
                    ("little-fox", "Little Fox"),
                    ("night-city", "Night City"),
                    ("orange-juice", "Orange Juice"),
                    ("passion", "Passion"),
                    ("pink-love", "Pink Love"),
                ],
                default="default",
                help_text="Color theme preference",
                max_length=20,
            ),
        ),
    ]
