# Generated by Django 5.1.7 on 2025-04-01 01:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("battycoda_app", "0006_add_default_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="profile_image",
            field=models.ImageField(blank=True, help_text="Profile image", null=True, upload_to="profile_images/"),
        ),
    ]
