# Generated by Django 5.2.1 on 2025-05-26 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("battycoda_app", "0007_add_spectrogram_job_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="annotated_at",
            field=models.DateTimeField(blank=True, help_text="When the annotation was completed", null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="annotated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who provided the annotation/label",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="annotated_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
