# Generated by Django 5.1.7 on 2025-04-01 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("battycoda_app", "0007_userprofile_profile_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="classifier",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this classifier",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_classifiers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="classifier",
            name="model_file",
            field=models.CharField(
                blank=True, help_text="Path to the model file for custom trained classifiers", max_length=512, null=True
            ),
        ),
        migrations.AddField(
            model_name="classifier",
            name="source_task_batch",
            field=models.ForeignKey(
                blank=True,
                help_text="The task batch that was used to train this classifier",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="derived_classifiers",
                to="battycoda_app.taskbatch",
            ),
        ),
        migrations.CreateModel(
            name="ClassifierTrainingJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Name for this training job", max_length=255)),
                ("description", models.TextField(blank=True, help_text="Description of the training job", null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "response_format",
                    models.CharField(
                        choices=[
                            ("full_probability", "Full Probability Distribution"),
                            ("highest_only", "Highest Probability Only"),
                        ],
                        default="highest_only",
                        help_text="Format of the response returned by this classifier",
                        max_length=20,
                    ),
                ),
                ("parameters", models.JSONField(blank=True, help_text="JSON with training parameters", null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("progress", models.FloatField(default=0.0, help_text="Progress percentage from 0-100")),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "classifier",
                    models.ForeignKey(
                        blank=True,
                        help_text="The classifier created by this training job (set after successful completion)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="training_job",
                        to="battycoda_app.classifier",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_jobs",
                        to="battycoda_app.group",
                    ),
                ),
                (
                    "task_batch",
                    models.ForeignKey(
                        help_text="The task batch used for training this classifier",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_jobs",
                        to="battycoda_app.taskbatch",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
