# Generated by Django 5.2.1 on 2025-05-28 00:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("battycoda_app", "0008_task_annotated_at_task_annotated_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="detectionrun",
            name="features_file",
            field=models.CharField(
                blank=True, help_text="Path to the exported features CSV file", max_length=512, null=True
            ),
        ),
    ]
