# Generated by Django 5.1.7 on 2025-04-01 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("battycoda_app", "0008_classifier_created_by_classifier_model_file_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserNotification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(help_text="Title of the notification", max_length=255)),
                ("message", models.TextField(help_text="Notification message content")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("segmentation", "Segmentation Notification"),
                            ("classification", "Classification Notification"),
                            ("system", "System Notification"),
                            ("info", "Information"),
                        ],
                        default="info",
                        help_text="Type of notification",
                        max_length=20,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("s7-check", "Success"),
                            ("s7-close", "Error"),
                            ("s7-info", "Info"),
                            ("s7-attention", "Warning"),
                            ("s7-bell", "Notification"),
                        ],
                        default="s7-bell",
                        help_text="Icon to display with notification",
                        max_length=20,
                    ),
                ),
                (
                    "link",
                    models.CharField(
                        blank=True, help_text="Optional link to view related content", max_length=512, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False, help_text="Whether the notification has been read")),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who will receive this notification",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
