# Generated by Django 5.1.7 on 2025-04-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("battycoda_app", "0009_usernotification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usernotification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("segmentation", "Segmentation Notification"),
                    ("classification", "Classification Notification"),
                    ("training", "Classifier Training Notification"),
                    ("system", "System Notification"),
                    ("info", "Information"),
                ],
                default="info",
                help_text="Type of notification",
                max_length=20,
            ),
        ),
    ]
