# Generated by Django for BattyCoda

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battycoda_app', '0009_add_features_file_to_detection_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='api_key',
            field=models.CharField(blank=True, help_text='API key for programmatic access', max_length=40, null=True, unique=True),
        ),
    ]