# Generated by Django 5.2.1 on 2025-06-27 02:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("battycoda_app", "0010_add_api_key_to_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detectionrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
