# Generated by Django on 2025-01-07

from django.db import migrations

def create_rousettus_aegyptiacus_species(apps, schema_editor):
    """
    Create Rousettus aegyptiacus species with its call types.
    """
    import os
    from django.core.files import File
    
    Species = apps.get_model('battycoda_app', 'Species')
    Call = apps.get_model('battycoda_app', 'Call')
    User = apps.get_model('auth', 'User')
    
    # Get admin user or first user
    admin_user = User.objects.filter(is_superuser=True).first() or User.objects.first()
    
    # Create Rousettus aegyptiacus species
    rousettus = Species.objects.create(
        name="Rousettus aegyptiacus",
        description="Rousettus aegyptiacus (Egyptian fruit bat) is a megabat species found in Africa and the Middle East. They are known for their diverse vocal repertoire including trills, barks, pitchy calls, and various other vocalizations used for communication.",
        created_by=admin_user,
        group=None,
        is_system=True
    )
    
    # Add image for Rousettus aegyptiacus if available
    image_path = "/app/data/species_images/Rousettus.png"
    if os.path.exists(image_path):
        with open(image_path, "rb") as img_file:
            rousettus.image.save("Rousettus.png", File(img_file), save=True)
    
    # Call types for Rousettus aegyptiacus
    rousettus_calls = [
        ("Tr", "Trill"),
        ("Ba", "Bark"),
        ("Pi", "Pitchy Call"),
        ("LPi", "Loud Pitchy Call"),
        ("Bu", "Low Buzz"),
        ("Pa", "Panting"),
        ("LT", "Low Tuck"),
        ("Sq", "Squeal"),
        ("Ra", "Rattle"),
        ("Ch", "Chuckles"),
        ("BB", "Bark Buzz"),
        ("PB", "Pitchy Call Buzz"),
        ("SB", "Squeal Buzz"),
        ("Un", "Unknown")
    ]
    
    for short_name, long_name in rousettus_calls:
        Call.objects.create(
            species=rousettus, 
            short_name=short_name, 
            long_name=long_name
        )

def reverse_rousettus_aegyptiacus_species(apps, schema_editor):
    """
    Remove Rousettus aegyptiacus species and its call types.
    """
    Species = apps.get_model('battycoda_app', 'Species')
    Call = apps.get_model('battycoda_app', 'Call')
    
    try:
        rousettus = Species.objects.get(name="Rousettus aegyptiacus", is_system=True)
        # Delete all calls for this species first
        Call.objects.filter(species=rousettus).delete()
        # Delete the species
        rousettus.delete()
    except Species.DoesNotExist:
        pass

class Migration(migrations.Migration):
    dependencies = [
        ('battycoda_app', '0011_add_queued_status_to_detection_run'),
    ]

    operations = [
        migrations.RunPython(
            create_rousettus_aegyptiacus_species,
            reverse_rousettus_aegyptiacus_species
        ),
    ]