# Generated by Django 5.2.1 on 2025-07-06 21:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("battycoda_app", "0012_add_rousettus_aegyptiacus"),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DetectionRun',
            new_name='ClassificationRun',
        ),
        migrations.RenameModel(
            old_name='DetectionResult',
            new_name='ClassificationResult',
        ),
    ]
