# Generated by Django 5.2.3 on 2025-07-17 23:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("battycoda_app", "0014_auto_20250716_1838"),
    ]

    operations = [
        # Rename detection_run_id column to classification_run_id in ClassificationResult table
        migrations.RunSQL(
            "ALTER TABLE battycoda_app_classificationresult RENAME COLUMN detection_run_id TO classification_run_id;",
            reverse_sql="ALTER TABLE battycoda_app_classificationresult RENAME COLUMN classification_run_id TO detection_run_id;"
        ),
    ]
