# Generated by Django 5.2.3 on 2025-07-17 23:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("battycoda_app", "0014_auto_20250716_1838"),
    ]

    operations = [
        migrations.RenameField(
            model_name='classificationresult',
            old_name='detection_run',
            new_name='classification_run',
        ),
    ]
