# Generated by Django 5.2.3 on 2025-07-18 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("battycoda_app", "0015_auto_20250717_2356"),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True, help_text="Last time the user performed any significant action"),
        ),
    ]
