# Generated by Django 5.2.3 on 2025-07-25 01:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("battycoda_app", "0016_add_last_activity_field"),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='management_features_enabled',
            field=models.BooleanField(default=False, help_text="Enable access to management and administrative features"),
        ),
    ]
