# Generated by Django 5.2.3 on 2025-07-25 01:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("battycoda_app", "0017_add_management_features_flag"),
    ]

    operations = []
