# Generated by Django 5.2.3 on 2025-09-16 01:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("battycoda_app", "0018_resolve_migration_conflicts"),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE battycoda_app_callprobability RENAME COLUMN detection_result_id TO classification_result_id;",
            reverse_sql="ALTER TABLE battycoda_app_callprobability RENAME COLUMN classification_result_id TO detection_result_id;"
        ),
    ]
