# Generated by Django 5.2.3 on 2025-09-16 01:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("battycoda_app", "0018_resolve_migration_conflicts"),
    ]

    operations = [
        migrations.RenameField(
            model_name='callprobability',
            old_name='detection_result',
            new_name='classification_result',
        ),
    ]
