# Generated by Django 5.2.3 on 2025-09-27 12:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("battycoda_app", "0019_auto_20250916_0117"),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskbatch',
            old_name='detection_run',
            new_name='classification_run',
        ),
    ]
