# Generated by Django 5.2.3 on 2025-09-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("battycoda_app", "0020_rename_detection_run_to_classification_run"),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='spectrogram_file',
            field=models.CharField(blank=True, help_text='Filename of the generated spectrogram PNG', max_length=255, null=True),
        ),
    ]
