# Generated by Django 5.2.3 on 2025-09-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("battycoda_app", "0021_add_spectrogram_file_to_recording"),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='hidden',
            field=models.BooleanField(default=False, help_text='Hidden recordings are temporary previews that don\'t appear in normal lists'),
        ),
    ]
