# Generated by Django 5.2.6 on 2025-10-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("battycoda_app", "0024_rename_detection_result_callprobability_classification_result_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="species",
            name="detail_padding_end_ms",
            field=models.IntegerField(
                default=8, help_text="Padding in milliseconds after the call in detail view spectrograms"
            ),
        ),
        migrations.AddField(
            model_name="species",
            name="detail_padding_start_ms",
            field=models.IntegerField(
                default=8, help_text="Padding in milliseconds before the call in detail view spectrograms"
            ),
        ),
        migrations.AddField(
            model_name="species",
            name="overview_padding_end_ms",
            field=models.IntegerField(
                default=500, help_text="Padding in milliseconds after the call in overview spectrograms"
            ),
        ),
        migrations.AddField(
            model_name="species",
            name="overview_padding_start_ms",
            field=models.IntegerField(
                default=500, help_text="Padding in milliseconds before the call in overview spectrograms"
            ),
        ),
    ]
