# Generated by Django 5.2.6 on 2025-11-07 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("battycoda_app", "0025_species_detail_padding_end_ms_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="in_progress_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User currently working on this task",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks_in_progress",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="in_progress_since",
            field=models.DateTimeField(blank=True, help_text="When the user started working on this task", null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("in_progress", "In Progress"), ("done", "Done")],
                default="pending",
                max_length=20,
            ),
        ),
    ]
