# Generated by Django 5.2.6 on 2025-11-10 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("battycoda_app", "0026_task_status_and_progress_tracking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classifiertrainingjob",
            name="task_batch",
            field=models.ForeignKey(
                blank=True,
                help_text="The task batch used for training this classifier (null if trained from folder)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="training_jobs",
                to="battycoda_app.taskbatch",
            ),
        ),
    ]
