# Generated by Django 5.2.6 on 2026-01-13 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("battycoda_app", "0027_make_task_batch_nullable_in_training_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="clusteringrun",
            name="batch_size",
            field=models.IntegerField(
                default=500, help_text="Number of segments to process per batch for memory management"
            ),
        ),
        migrations.AddField(
            model_name="clusteringrun",
            name="progress_message",
            field=models.CharField(
                blank=True, default="", help_text="Detailed progress message for UI feedback", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="clusteringrun",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="The project containing recordings to cluster (project-wide mode)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clustering_runs",
                to="battycoda_app.project",
            ),
        ),
        migrations.AddField(
            model_name="clusteringrun",
            name="scope",
            field=models.CharField(
                choices=[("segmentation", "Single Segmentation"), ("project", "Entire Project")],
                default="segmentation",
                help_text="Whether clustering is for a single segmentation or entire project",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="clusteringrun",
            name="species",
            field=models.ForeignKey(
                blank=True,
                help_text="Species to include (required for project-level clustering)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clustering_runs",
                to="battycoda_app.species",
            ),
        ),
        migrations.AlterField(
            model_name="clusteringrun",
            name="segmentation",
            field=models.ForeignKey(
                blank=True,
                help_text="The segmentation containing segments to cluster (single-file mode)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clustering_runs",
                to="battycoda_app.segmentation",
            ),
        ),
        migrations.CreateModel(
            name="ClusteringRunSegmentation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "segments_count",
                    models.IntegerField(
                        default=0, help_text="Number of segments from this segmentation included in the run"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("included", "Included"), ("skipped", "Skipped")],
                        default="included",
                        help_text="Whether this segmentation was included or skipped",
                        max_length=20,
                    ),
                ),
                (
                    "clustering_run",
                    models.ForeignKey(
                        help_text="The clustering run this segmentation was included in",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="included_segmentations",
                        to="battycoda_app.clusteringrun",
                    ),
                ),
                (
                    "segmentation",
                    models.ForeignKey(
                        help_text="The segmentation included in the clustering run",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="included_in_clustering_runs",
                        to="battycoda_app.segmentation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clustering Run Segmentation",
                "verbose_name_plural": "Clustering Run Segmentations",
                "unique_together": {("clustering_run", "segmentation")},
            },
        ),
    ]
