# Generated by Django 5.2.10 on 2026-01-17 15:31

from django.db import migrations, models


def migrate_themes_forward(apps, schema_editor):
    """Migrate old theme values to new light/dark scheme."""
    UserProfile = apps.get_model('battycoda_app', 'UserProfile')

    # Map old themes to new ones
    # night-city was the darkest theme, map it to dark
    # everything else maps to light
    dark_themes = {'night-city'}

    for profile in UserProfile.objects.all():
        if profile.theme in dark_themes:
            profile.theme = 'dark'
        else:
            profile.theme = 'light'
        profile.save(update_fields=['theme'])


def migrate_themes_reverse(apps, schema_editor):
    """Reverse migration - map back to default."""
    UserProfile = apps.get_model('battycoda_app', 'UserProfile')

    for profile in UserProfile.objects.all():
        if profile.theme == 'dark':
            profile.theme = 'night-city'
        else:
            profile.theme = 'default'
        profile.save(update_fields=['theme'])


class Migration(migrations.Migration):

    dependencies = [
        ('battycoda_app', '0028_project_level_clustering'),
    ]

    operations = [
        # First migrate the data
        migrations.RunPython(migrate_themes_forward, migrate_themes_reverse),
        # Then change the field constraints
        migrations.AlterField(
            model_name='userprofile',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', help_text='Color theme preference', max_length=20),
        ),
    ]
