# Generated by Django 5.2.10 on 2026-01-17 19:53

from django.db import migrations, models


def convert_nulls_to_empty_strings(apps, schema_editor):
    """Convert NULL values to empty strings for all affected string fields."""
    # List of (model_name, field_name) tuples to convert
    fields_to_convert = [
        ('Call', 'long_name'),
        ('ClassificationRun', 'error_message'),
        ('ClassificationRun', 'features_file'),
        ('Classifier', 'description'),
        ('Classifier', 'endpoint'),
        ('Classifier', 'model_file'),
        ('Classifier', 'service_url'),
        ('ClassifierTrainingJob', 'description'),
        ('ClassifierTrainingJob', 'error_message'),
        ('Cluster', 'description'),
        ('Cluster', 'label'),
        ('ClusterCallMapping', 'notes'),
        ('ClusteringAlgorithm', 'description'),
        ('ClusteringAlgorithm', 'endpoint'),
        ('ClusteringAlgorithm', 'service_url'),
        ('ClusteringRun', 'description'),
        ('ClusteringRun', 'error_message'),
        ('ClusteringRun', 'task_id'),
        ('Group', 'description'),
        ('Project', 'description'),
        ('Recording', 'description'),
        ('Recording', 'environmental_conditions'),
        ('Recording', 'equipment'),
        ('Recording', 'location'),
        ('Recording', 'spectrogram_file'),
        ('Segment', 'name'),
        ('Segment', 'notes'),
        ('Segmentation', 'error_message'),
        ('Segmentation', 'task_id'),
        ('SegmentationAlgorithm', 'description'),
        ('SegmentationAlgorithm', 'endpoint'),
        ('SegmentationAlgorithm', 'service_url'),
        ('Species', 'description'),
        ('SpectrogramJob', 'celery_task_id'),
        ('SpectrogramJob', 'error_message'),
        ('SpectrogramJob', 'output_file_path'),
        ('SpectrogramJob', 'output_file_url'),
        ('Task', 'classification_result'),
        ('Task', 'label'),
        ('Task', 'notes'),
        ('TaskBatch', 'description'),
        ('UserNotification', 'link'),
        ('UserProfile', 'cloudflare_email'),
        ('UserProfile', 'cloudflare_id'),
    ]

    for model_name, field_name in fields_to_convert:
        Model = apps.get_model('battycoda_app', model_name)
        Model.objects.filter(**{f'{field_name}__isnull': True}).update(**{field_name: ''})


def reverse_noop(apps, schema_editor):
    """Reverse migration is a no-op - we can't distinguish original NULLs from converted ones."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('battycoda_app', '0029_simplify_themes'),
    ]

    operations = [
        # First, convert all NULL values to empty strings
        migrations.RunPython(convert_nulls_to_empty_strings, reverse_noop),
        # Then alter the field definitions
        migrations.AlterField(
            model_name='call',
            name='long_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='classificationrun',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='classificationrun',
            name='features_file',
            field=models.CharField(blank=True, default='', help_text='Path to the exported features CSV file', max_length=512),
        ),
        migrations.AlterField(
            model_name='classifier',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Description of how the algorithm works'),
        ),
        migrations.AlterField(
            model_name='classifier',
            name='endpoint',
            field=models.CharField(blank=True, default='', help_text='Endpoint path for the service', max_length=255),
        ),
        migrations.AlterField(
            model_name='classifier',
            name='model_file',
            field=models.CharField(blank=True, default='', help_text='Path to the model file for custom trained classifiers', max_length=512),
        ),
        migrations.AlterField(
            model_name='classifier',
            name='service_url',
            field=models.CharField(blank=True, default='', help_text='URL of the external service, if applicable', max_length=255),
        ),
        migrations.AlterField(
            model_name='classifiertrainingjob',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Description of the training job'),
        ),
        migrations.AlterField(
            model_name='classifiertrainingjob',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Description of the acoustic pattern in this cluster'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='label',
            field=models.CharField(blank=True, default='', help_text='Expert-assigned label for this cluster', max_length=255),
        ),
        migrations.AlterField(
            model_name='clustercallmapping',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Notes about this mapping'),
        ),
        migrations.AlterField(
            model_name='clusteringalgorithm',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Description of how the algorithm works'),
        ),
        migrations.AlterField(
            model_name='clusteringalgorithm',
            name='endpoint',
            field=models.CharField(blank=True, default='', help_text='Endpoint path for the service', max_length=255),
        ),
        migrations.AlterField(
            model_name='clusteringalgorithm',
            name='service_url',
            field=models.CharField(blank=True, default='', help_text='URL of the external service, if applicable', max_length=255),
        ),
        migrations.AlterField(
            model_name='clusteringrun',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Description of this clustering run'),
        ),
        migrations.AlterField(
            model_name='clusteringrun',
            name='error_message',
            field=models.TextField(blank=True, default='', help_text='Error message if the run failed'),
        ),
        migrations.AlterField(
            model_name='clusteringrun',
            name='task_id',
            field=models.CharField(blank=True, default='', help_text='Celery task ID for this clustering run', max_length=100),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='recording',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Description of the recording'),
        ),
        migrations.AlterField(
            model_name='recording',
            name='environmental_conditions',
            field=models.TextField(blank=True, default='', help_text='Environmental conditions during recording'),
        ),
        migrations.AlterField(
            model_name='recording',
            name='equipment',
            field=models.CharField(blank=True, default='', help_text='Equipment used for recording', max_length=255),
        ),
        migrations.AlterField(
            model_name='recording',
            name='location',
            field=models.CharField(blank=True, default='', help_text='Location where the recording was made', max_length=255),
        ),
        migrations.AlterField(
            model_name='recording',
            name='spectrogram_file',
            field=models.CharField(blank=True, default='', help_text='Filename of the generated spectrogram PNG', max_length=255),
        ),
        migrations.AlterField(
            model_name='segment',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Optional name for this segment', max_length=255),
        ),
        migrations.AlterField(
            model_name='segment',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Notes about this segment'),
        ),
        migrations.AlterField(
            model_name='segmentation',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='segmentation',
            name='task_id',
            field=models.CharField(blank=True, default='', help_text='Celery task ID for automated segmentation', max_length=100),
        ),
        migrations.AlterField(
            model_name='segmentationalgorithm',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Description of how the algorithm works'),
        ),
        migrations.AlterField(
            model_name='segmentationalgorithm',
            name='endpoint',
            field=models.CharField(blank=True, default='', help_text='Endpoint path for the service', max_length=255),
        ),
        migrations.AlterField(
            model_name='segmentationalgorithm',
            name='service_url',
            field=models.CharField(blank=True, default='', help_text='URL of the external service, if applicable', max_length=255),
        ),
        migrations.AlterField(
            model_name='species',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='spectrogramjob',
            name='celery_task_id',
            field=models.CharField(blank=True, default='', help_text='Celery task ID for tracking the background job', max_length=255),
        ),
        migrations.AlterField(
            model_name='spectrogramjob',
            name='error_message',
            field=models.TextField(blank=True, default='', help_text='Error message if the job failed'),
        ),
        migrations.AlterField(
            model_name='spectrogramjob',
            name='output_file_path',
            field=models.CharField(blank=True, default='', help_text='Path to the generated spectrogram file', max_length=500),
        ),
        migrations.AlterField(
            model_name='spectrogramjob',
            name='output_file_url',
            field=models.CharField(blank=True, default='', help_text='URL to access the generated spectrogram', max_length=500),
        ),
        migrations.AlterField(
            model_name='task',
            name='classification_result',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='label',
            field=models.CharField(blank=True, default='', help_text='Final expert label assigned to this task', max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Additional notes or observations about this task'),
        ),
        migrations.AlterField(
            model_name='taskbatch',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='link',
            field=models.CharField(blank=True, default='', help_text='Optional link to view related content', max_length=512),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cloudflare_email',
            field=models.EmailField(blank=True, default='', help_text='Deprecated - kept for data compatibility', max_length=254),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cloudflare_id',
            field=models.CharField(blank=True, default='', help_text='Deprecated - kept for data compatibility', max_length=255),
        ),
    ]
