# Generated by Django 5.2.10 on 2026-02-11 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battycoda_app', '0031_recording_processing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segmentation',
            name='min_duration_ms',
            field=models.FloatField(default=10),
        ),
        migrations.AlterField(
            model_name='segmentationalgorithm',
            name='default_min_duration_ms',
            field=models.FloatField(default=10, help_text='Default minimum duration in milliseconds'),
        ),
    ]
