# Generated by Django 5.2.10 on 2026-02-12 12:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battycoda_app', '0032_change_min_duration_to_float'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TusUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('upload_length', models.BigIntegerField(help_text='Total file size in bytes declared by client')),
                ('upload_offset', models.BigIntegerField(default=0, help_text='Bytes received so far')),
                ('temp_file_path', models.CharField(help_text='Path to temporary file accumulating chunks', max_length=512)),
                ('filename', models.CharField(help_text='Original filename from Upload-Metadata', max_length=255)),
                ('content_type', models.CharField(default='application/octet-stream', max_length=100)),
                ('metadata_json', models.JSONField(blank=True, default=dict, help_text='Recording metadata (species_id, project_id, name, etc.)')),
                ('is_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tus_uploads', to='battycoda_app.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tus_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
