version: '3.8'

services:
  web:
    image: python:3.12-slim
    network_mode: host
    volumes:
      - ./:/app:rw
      - data-volume:/app/media:rw
      - /home/ubuntu/template:/template:ro
      - ./data:/data:rw
    working_dir: /app
    env_file:
      - .env.local
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - REDIS_URL=redis://localhost:6379/0
      - CELERY_BROKER_URL=redis://localhost:6379/0
      - CELERY_RESULT_BACKEND=redis://localhost:6379/0
      - AWS_SES_REGION_NAME=${AWS_SES_REGION_NAME}
      - AWS_SES_ACCESS_KEY_ID=${AWS_SES_ACCESS_KEY_ID}
      - AWS_SES_SECRET_ACCESS_KEY=${AWS_SES_SECRET_ACCESS_KEY}
      - AWS_SES_CONFIGURATION_SET=${AWS_SES_CONFIGURATION_SET}
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL}
    depends_on:
      - redis
    restart: unless-stopped
    command: >
      bash -c "
        echo 'Installing dependencies...' &&
        pip install -r requirements.txt &&
        echo 'Starting web server...' &&
        gunicorn --workers=3 --bind=0.0.0.0:8060 --timeout=120 --log-level debug config.wsgi:application
      "

  celery:
    image: python:3.12-slim
    network_mode: host
    volumes:
      - ./:/app:rw
      - data-volume:/app/media:rw
      - /home/ubuntu/template:/template:ro
    working_dir: /app
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - REDIS_URL=redis://localhost:6379/0
      - CELERY_BROKER_URL=redis://localhost:6379/0
      - CELERY_RESULT_BACKEND=redis://localhost:6379/0
      - AWS_SES_REGION_NAME=${AWS_SES_REGION_NAME}
      - AWS_SES_ACCESS_KEY_ID=${AWS_SES_ACCESS_KEY_ID}
      - AWS_SES_SECRET_ACCESS_KEY=${AWS_SES_SECRET_ACCESS_KEY}
      - AWS_SES_CONFIGURATION_SET=${AWS_SES_CONFIGURATION_SET}
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL}
    depends_on:
      - redis
    restart: unless-stopped
    command: >
      bash -c "
        echo 'Installing dependencies...' &&
        pip install -r requirements.txt &&
        echo 'Starting Celery worker...' &&
        celery -A config worker --loglevel=info
      "

  flower:
    image: python:3.12-slim
    network_mode: host
    volumes:
      - ./:/app:rw
    working_dir: /app
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - REDIS_URL=redis://localhost:6379/0
      - CELERY_BROKER_URL=redis://localhost:6379/0
      - CELERY_RESULT_BACKEND=redis://localhost:6379/0
    depends_on:
      - redis
      - celery
    restart: unless-stopped
    command: >
      bash -c "
        echo 'Installing dependencies...' &&
        pip install -r requirements.txt &&
        echo 'Starting Flower...' &&
        celery -A config flower --port=5555
      "

  redis:
    image: redis:latest
    network_mode: host
    volumes:
      - redis-data:/data
    restart: unless-stopped

  r-server-direct:
    image: rocker/r-base:latest
    ports:
      - "8100:8100"
    volumes:
      - ./:/app:rw
      - r-libs:/usr/local/lib/R/site-library
    working_dir: /app
    restart: unless-stopped
    command: >
      bash -c "
        Rscript r_server_direct.R
      "

  r-server-original:
    image: rocker/r-base:latest
    ports:
      - "8101:8101"
    volumes:
      - ./:/app:rw
      - r-libs:/usr/local/lib/R/site-library
    working_dir: /app
    restart: unless-stopped
    command: >
      bash -c "
        Rscript r_prediction_server.R --port 8101
      "

volumes:
  data-volume:
  redis-data:
  r-libs: