# BattyCoda Docker Compose Configuration
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    network_mode: host
    volumes:
      - ./:/app:rw
      - data-volume:/app/media:rw
      - /home/ubuntu/template:/template:ro
      - ./data:/data:rw
    env_file:
      - .env
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - REDIS_URL=redis://localhost:6379/0
      - CELERY_BROKER_URL=redis://localhost:6379/0
      - CELERY_RESULT_BACKEND=redis://localhost:6379/0
    depends_on:
      - redis
    restart: unless-stopped

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    network_mode: host
    volumes:
      - ./:/app:rw
      - data-volume:/app/media:rw
      - /home/ubuntu/template:/template:ro
    env_file:
      - .env
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - REDIS_URL=redis://localhost:6379/0
      - CELERY_BROKER_URL=redis://localhost:6379/0
      - CELERY_RESULT_BACKEND=redis://localhost:6379/0
    depends_on:
      - redis
    restart: unless-stopped

  flower:
    build:
      context: .
      dockerfile: Dockerfile.flower
    network_mode: host
    volumes:
      - ./:/app:rw
    env_file:
      - .env
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - REDIS_URL=redis://localhost:6379/0
      - CELERY_BROKER_URL=redis://localhost:6379/0
      - CELERY_RESULT_BACKEND=redis://localhost:6379/0
    depends_on:
      - redis
      - celery
    restart: unless-stopped

  redis:
    image: redis:latest
    network_mode: host
    volumes:
      - redis-data:/data
    restart: unless-stopped

  r-server-direct:
    build:
      context: .
      dockerfile: Dockerfile.r_full
    network_mode: host  # Use host network mode for direct port access
    volumes:
      - ./:/app:rw  # Mount project directory to access R scripts
      - r-libs:/usr/local/lib/R/site-library  # Persist R package installations
    restart: unless-stopped

volumes:
  data-volume:
  redis-data:
  r-libs: