# BattyCoda Docker Compose Configuration
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    network_mode: host
    user: "1000:1000"  # Set to match the host user to fix permission issues
    volumes:
      - ./:/app:rw
    env_file:
      - .env
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - REDIS_URL=redis://localhost:6379/0
      - CELERY_BROKER_URL=redis://localhost:6379/0
      - CELERY_RESULT_BACKEND=redis://localhost:6379/0
      - DATABASE_URL=postgres://battycoda:battycoda@localhost:5432/battycoda
    depends_on:
      - redis
      - db
    restart: unless-stopped

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    network_mode: host
    user: "1000:1000"  # Set to match the host user to fix permission issues
    volumes:
      - ./:/app:rw
    env_file:
      - .env
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - REDIS_URL=redis://localhost:6379/0
      - CELERY_BROKER_URL=redis://localhost:6379/0
      - CELERY_RESULT_BACKEND=redis://localhost:6379/0
    depends_on:
      - redis
    restart: unless-stopped

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile.celery
    network_mode: host
    user: "1000:1000"  # Set to match the host user to fix permission issues
    volumes:
      - ./:/app:rw
    env_file:
      - .env
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - REDIS_URL=redis://localhost:6379/0
      - CELERY_BROKER_URL=redis://localhost:6379/0
      - CELERY_RESULT_BACKEND=redis://localhost:6379/0
    depends_on:
      - redis
      - celery
    restart: unless-stopped
    command: ["celery", "-A", "config", "beat", "--loglevel=info", "--schedule=/tmp/celerybeat-schedule"]

  flower:
    build:
      context: .
      dockerfile: Dockerfile.flower
    network_mode: host
    user: "1000:1000"  # Set to match the host user to fix permission issues
    volumes:
      - ./:/app:rw
    env_file:
      - .env
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - REDIS_URL=redis://localhost:6379/0
      - CELERY_BROKER_URL=redis://localhost:6379/0
      - CELERY_RESULT_BACKEND=redis://localhost:6379/0
    depends_on:
      - redis
      - celery
    restart: unless-stopped

  redis:
    image: redis:latest
    network_mode: host
    volumes:
      - redis-data:/data
    restart: unless-stopped
    
  db:
    image: postgres:15
    network_mode: host
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=battycoda
      - POSTGRES_USER=battycoda
      - POSTGRES_PASSWORD=battycoda
    restart: unless-stopped

  r-server:
    build:
      context: .
      dockerfile: Dockerfile.r_ubuntu
    network_mode: host  # Use host network mode for direct port access
    user: "1000:1000"  # Set to match the host user to fix permission issues
    volumes:
      - ./:/app:rw  # Mount project directory to access R scripts
    restart: unless-stopped
    command: ["Rscript", "server.R", "--port=8001"]

volumes:
  redis-data:
  postgres-data: