"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
import sys
from pathlib import Path

import dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env
env_file = BASE_DIR / ".env"
if env_file.exists():
    dotenv.load_dotenv(env_file)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# The SECRET_KEY must be provided via environment variable
SECRET_KEY = os.environ.get("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
# Debug mode should be False in production
DEBUG = os.environ.get("DEBUG", "False").lower() == "true"

# Detect test mode early (needed for security settings below)
# DJANGO_TEST_MODE env var or Django's built-in test runner
DJANGO_TEST_MODE = os.environ.get("DJANGO_TEST_MODE", "false").lower() == "true" or "test" in sys.argv

# Admin email notifications for 500 errors
ADMINS = [
    ("Kevin Boergens", "kevin.boergens@gmail.com"),
    ("Kevin Boergens Alt", "amazon@boerg.e4ward.com"),  # Verified in SES
]
MANAGERS = ADMINS

# Get domain name from environment
DOMAIN_NAME = os.environ.get("DOMAIN_NAME", "localhost")

# Allow the domain name, www subdomain, localhost, and internal docker IPs
ALLOWED_HOSTS = [DOMAIN_NAME, f"www.{DOMAIN_NAME}", "localhost", "127.0.0.1", "[::1]"]

# Add public IP for AWS deployments
from .aws_utils import get_public_ip

public_ip = get_public_ip()
if public_ip:
    ALLOWED_HOSTS.append(public_ip)

# CSRF trusted origins - generated dynamically based on DOMAIN_NAME
CSRF_TRUSTED_ORIGINS = [
    f"https://{DOMAIN_NAME}",
    f"https://*.{DOMAIN_NAME}",
    f"http://{DOMAIN_NAME}",
    f"http://*.{DOMAIN_NAME}",
    "http://localhost",
    "http://127.0.0.1",
]

# Security settings for HTTPS
# SECURE_PROXY_SSL_HEADER tells Django to trust X-Forwarded-Proto header from nginx
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# In production (DEBUG=False and not in test mode), enable all HTTPS security features
# In development (DEBUG=True) or test mode, disable to allow HTTP
_enable_https_security = not DEBUG and not DJANGO_TEST_MODE
if _enable_https_security:
    SECURE_SSL_REDIRECT = True  # Redirect HTTP to HTTPS (nginx also does this)
    SESSION_COOKIE_SECURE = True  # Only send session cookie over HTTPS
    CSRF_COOKIE_SECURE = True  # Only send CSRF cookie over HTTPS
    SECURE_HSTS_SECONDS = 31536000  # 1 year HSTS (nginx also sends this)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
else:
    # Development/test mode - allow HTTP
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_HSTS_SECONDS = 0

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_vite",
    "battycoda_app",
    "hijack",
]

# Settings for django-hijack
HIJACK_LOGIN_REDIRECT_URL = "/"  # Where to redirect after hijacking
HIJACK_LOGOUT_REDIRECT_URL = "/admin/auth/user/"  # Where to redirect after releasing the user
HIJACK_ALLOW_GET_REQUESTS = False  # Do not allow GET requests for hijacking
HIJACK_USE_BOOTSTRAP = True  # Use Bootstrap for styling
HIJACK_INSERT_BEFORE = "</body>"  # Insert notification before closing body tag

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "csp.middleware.CSPMiddleware",  # Content Security Policy
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Add whitenoise for static files in production
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # Hijack middleware for user impersonation
    "hijack.middleware.HijackUserMiddleware",
    # Add standard authentication middleware
    "battycoda_app.middleware.authentication_middleware.AuthenticationMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "battycoda_app.context_processors.theme_choices",
                "battycoda_app.context_processors.hijack_notification",
                "battycoda_app.context_processors.sentry_settings",
                "battycoda_app.context_processors.vite_features",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
import dj_database_url

# Parse the production database URL to extract credentials
_prod_db_config = dj_database_url.config(
    default="postgres://battycoda:battycoda@localhost:5432/battycoda", conn_max_age=600
)

# Use separate test database for E2E tests to avoid polluting development data
if DJANGO_TEST_MODE:
    # Test database configuration - use same credentials as production, just different database name
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("DB_TEST_NAME", "battycoda_test"),
            "USER": _prod_db_config.get("USER", "battycoda"),
            "PASSWORD": _prod_db_config.get("PASSWORD", "battycoda"),
            "HOST": _prod_db_config.get("HOST", "localhost"),
            "PORT": _prod_db_config.get("PORT", "5432"),
        }
    }
else:
    # Use PostgreSQL exclusively - no fallbacks
    DATABASES = {"default": _prod_db_config}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Whitenoise configuration for serving static files
# Check if static file caching should be disabled using environment variable
DISABLE_STATIC_CACHING = os.environ.get("DISABLE_STATIC_CACHING", "False").lower() == "true"

# Choose appropriate storage backend based on caching settings
if DISABLE_STATIC_CACHING:
    # Use basic storage with no caching for development
    STATICFILES_STORAGE = "whitenoise.storage.StaticFilesStorage"
    WHITENOISE_MAX_AGE = 0  # No caching
else:
    # Use compressed storage with long caching for production
    STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"
    WHITENOISE_MAX_AGE = 31536000  # 1 year in seconds

# Vite configuration
# VITE_DEV_MODE: When True (and DEBUG=True), assets load from Vite dev server (localhost:5173)
# When False or in production, assets load from the built manifest
VITE_DEV_MODE = os.environ.get("VITE_DEV_MODE", "True").lower() == "true"

# Media files
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Make sure the media directory exists
os.makedirs(MEDIA_ROOT / "audio_cache", exist_ok=True)
os.makedirs(MEDIA_ROOT / "home", exist_ok=True)
os.makedirs(MEDIA_ROOT / "profile_images", exist_ok=True)

# File upload settings - read from same environment variable as Nginx
MAX_UPLOAD_SIZE_MB = int(os.environ.get("MAX_UPLOAD_SIZE_MB", 100))
DATA_UPLOAD_MAX_MEMORY_SIZE = MAX_UPLOAD_SIZE_MB * 1024 * 1024  # Convert MB to bytes
FILE_UPLOAD_MAX_MEMORY_SIZE = DATA_UPLOAD_MAX_MEMORY_SIZE

# Celery configuration
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "redis://redis:6379/0")
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", "redis://redis:6379/0")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Audio processing configuration
# Configure cache directories with proper permissions - let permission errors surface
os.environ["LIBROSA_CACHE_DIR"] = "/tmp/librosa_cache"
os.environ["NUMBA_CACHE_DIR"] = "/tmp/numba_cache"
os.environ["MPLCONFIGDIR"] = "/tmp/matplotlib_config"

# Create cache directories - any permission errors will be visible
os.makedirs("/tmp/librosa_cache", mode=0o755, exist_ok=True)
os.makedirs("/tmp/numba_cache", mode=0o755, exist_ok=True)
os.makedirs("/tmp/matplotlib_config", mode=0o755, exist_ok=True)

# Set proper permissions - fail if we can't
os.chmod("/tmp/librosa_cache", 0o755)
os.chmod("/tmp/numba_cache", 0o755)
os.chmod("/tmp/matplotlib_config", 0o755)

# Logging Configuration
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
    },
    "filters": {
        "require_debug_false": {
            "()": "django.utils.log.RequireDebugFalse",
        },
        "skip_disallowed_host": {
            "()": "django.utils.log.CallbackFilter",
            "callback": lambda record: "Invalid HTTP_HOST header" not in record.getMessage(),
        },
    },
    "handlers": {
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "mail_admins": {
            "level": "ERROR",
            "class": "django.utils.log.AdminEmailHandler",
            "include_html": True,
            "filters": ["require_debug_false", "skip_disallowed_host"],
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "django.request": {
            "handlers": ["mail_admins"],
            "level": "ERROR",
            "propagate": False,
        },
        "django.security.DisallowedHost": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
    },
}

# AWS SES Email Configuration
# Use dummy backend in test mode to avoid sending real emails and suppress warnings
if DJANGO_TEST_MODE:
    EMAIL_BACKEND = "django.core.mail.backends.locmem.EmailBackend"
else:
    EMAIL_BACKEND = "django_ses.SESBackend"
AWS_SES_REGION_NAME = os.environ.get("AWS_SES_REGION_NAME", "us-east-1")
AWS_SES_ACCESS_KEY_ID = os.environ.get("AWS_SES_ACCESS_KEY_ID")
AWS_SES_SECRET_ACCESS_KEY = os.environ.get("AWS_SES_SECRET_ACCESS_KEY")
AWS_SES_CONFIGURATION_SET = os.environ.get("AWS_SES_CONFIGURATION_SET", "")
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", f"noreply@{DOMAIN_NAME}")
SERVER_EMAIL = DEFAULT_FROM_EMAIL  # Email address for error notifications

# Database Backup Configuration
DATABASE_BACKUP_BUCKET = os.environ.get("DATABASE_BACKUP_BUCKET", "backup-battycoda")
DATABASE_BACKUP_PREFIX = os.environ.get("DATABASE_BACKUP_PREFIX", "database-backups/")

# R Server path mapping (for Docker or local development)
# R_SERVER_BASE_PATH: The base path the R server sees for this project (e.g., '/app' in Docker)
# R_SERVER_TMP_DIR: The temp directory the R server uses (e.g., '/app/tmp' in Docker)
R_SERVER_BASE_PATH = os.environ.get("R_SERVER_BASE_PATH", str(BASE_DIR))
R_SERVER_TMP_DIR = os.environ.get("R_SERVER_TMP_DIR", os.path.join(str(BASE_DIR), "tmp"))

# Django REST Framework Configuration
REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 50,
}

# drf-spectacular Configuration
SPECTACULAR_SETTINGS = {
    "TITLE": "BattyCoda API",
    "DESCRIPTION": "API for BattyCoda - Animal Call Analysis Platform",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "SCHEMA_PATH_PREFIX": "/api/",
    "COMPONENT_SPLIT_REQUEST": True,
    "SORT_OPERATIONS": False,
}

# Sentry Error Tracking Configuration
SENTRY_DSN = os.environ.get("SENTRY_DSN")
SENTRY_ENVIRONMENT = os.environ.get("SENTRY_ENVIRONMENT", "production")

if SENTRY_DSN:
    import sentry_sdk
    from sentry_sdk.integrations.celery import CeleryIntegration
    from sentry_sdk.integrations.django import DjangoIntegration
    from sentry_sdk.integrations.logging import LoggingIntegration

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[
            DjangoIntegration(),
            CeleryIntegration(),
            LoggingIntegration(level=None, event_level=None),
        ],
        traces_sample_rate=0.1,
        send_default_pii=True,
        environment=SENTRY_ENVIRONMENT,
    )

# Vite Frontend Build Configuration
# Controls incremental migration from Django static files to Vite-bundled JS
VITE_ENABLED = os.environ.get("VITE_ENABLED", "false").lower() == "true"

# django-vite configuration
# See: https://github.com/MrBin99/django-vite
DJANGO_VITE = {
    "default": {
        # Manifest location (generated by vite build)
        "manifest_path": BASE_DIR / "static" / "dist" / ".vite" / "manifest.json",
        # Dev server settings (only used when VITE_DEV_MODE and DEBUG are both True)
        "dev_mode": DEBUG and VITE_DEV_MODE,
        "dev_server_host": "localhost",
        "dev_server_port": 5173,
        # Static file settings for production
        "static_url_prefix": "dist/",
    }
}

# Feature flags for per-feature Vite migration
# Each feature can be migrated independently with rollback capability
# Migration order (suggested by risk/complexity):
#   1. theme_switcher (low risk, low complexity)
#   2. notifications (low risk, low complexity)
#   3. datetime_formatter (low risk, low complexity)
#   4. file_upload (medium risk, medium complexity)
#   5. cluster_explorer (medium risk, high complexity)
#   6. cluster_mapping (medium risk, high complexity)
#   7. player (high risk, high complexity)
#   8. task_annotation (high risk, high complexity)
#   9. segmentation (medium risk, medium complexity)
VITE_FEATURES = {
    "theme_switcher": os.environ.get("VITE_FEATURE_THEME_SWITCHER", "false").lower() == "true",
    "notifications": os.environ.get("VITE_FEATURE_NOTIFICATIONS", "false").lower() == "true",
    "datetime_formatter": os.environ.get("VITE_FEATURE_DATETIME_FORMATTER", "false").lower() == "true",
    "file_upload": os.environ.get("VITE_FEATURE_FILE_UPLOAD", "false").lower() == "true",
    "cluster_explorer": os.environ.get("VITE_FEATURE_CLUSTER_EXPLORER", "false").lower() == "true",
    "cluster_mapping": os.environ.get("VITE_FEATURE_CLUSTER_MAPPING", "false").lower() == "true",
    "player": os.environ.get("VITE_FEATURE_PLAYER", "false").lower() == "true",
    "task_annotation": os.environ.get("VITE_FEATURE_TASK_ANNOTATION", "false").lower() == "true",
    "segmentation": os.environ.get("VITE_FEATURE_SEGMENTATION", "false").lower() == "true",
}

# =============================================================================
# Content Security Policy (CSP) Configuration
# =============================================================================
# django-csp docs: https://django-csp.readthedocs.io/
#
# CSP provides defense-in-depth against XSS attacks by restricting what
# resources can be loaded and executed on pages.
#
# IMPORTANT: Currently using 'unsafe-inline' for scripts and styles because
# the codebase has many inline scripts and styles. Future work should migrate
# to nonces or hashes to remove 'unsafe-inline'.
#
# CSP_ENFORCE: Controls whether CSP is enforced or report-only.
#   - false (default): Report-only mode - violations logged but not blocked
#   - true: Enforcement mode - violations are blocked
# =============================================================================

# By default, start in report-only mode to test without breaking functionality
# Set CSP_ENFORCE=true in .env when ready to enforce
CSP_ENFORCE = os.environ.get("CSP_ENFORCE", "false").lower() == "true"

# Define the CSP directives
_CSP_DIRECTIVES = {
    # Default fallback - restrict to same origin
    "default-src": ["'self'"],
    # Scripts: self + CDNs + unsafe-inline (needed for inline scripts)
    # TODO: Migrate to nonces to remove 'unsafe-inline' (see battycoda-xxx)
    "script-src": [
        "'self'",
        "'unsafe-inline'",  # Required for inline scripts - should be removed eventually
        "cdn.jsdelivr.net",  # Bootstrap, Perfect Scrollbar, Select2, Sortable.js
        "cdnjs.cloudflare.com",  # Font Awesome, Toastr
        "code.jquery.com",  # jQuery
        "js.sentry-cdn.com",  # Sentry error tracking
    ],
    # Styles: self + CDNs + unsafe-inline (needed for inline styles)
    "style-src": [
        "'self'",
        "'unsafe-inline'",  # Required for inline styles and some libraries
        "cdn.jsdelivr.net",  # Bootstrap CSS, Perfect Scrollbar CSS, Select2 CSS
        "cdnjs.cloudflare.com",  # Font Awesome CSS, Toastr CSS
        "fonts.googleapis.com",  # Google Fonts CSS
    ],
    # Images: self + data URIs (for inline images, spectrograms)
    "img-src": [
        "'self'",
        "data:",  # Data URIs for inline images
    ],
    # Fonts: self + CDNs
    "font-src": [
        "'self'",
        "cdnjs.cloudflare.com",  # Font Awesome fonts
        "fonts.gstatic.com",  # Google Fonts
    ],
    # AJAX/fetch/WebSocket connections
    "connect-src": [
        "'self'",
        "*.sentry.io",  # Sentry error reporting
        "*.ingest.sentry.io",  # Sentry ingest endpoint
    ],
    # Frames: restrict to same origin (or 'none' if no iframes needed)
    "frame-src": ["'self'"],
    # Frame ancestors: who can embed this site in an iframe
    "frame-ancestors": ["'self'"],
    # Form submissions: restrict to same origin
    "form-action": ["'self'"],
    # Base URI: restrict base tag to same origin
    "base-uri": ["'self'"],
    # Object/embed: disable plugins (Flash, etc.)
    "object-src": ["'none'"],
}

# Development mode: allow Vite dev server
if DEBUG and VITE_DEV_MODE:
    # Add Vite dev server to allowed sources
    _CSP_DIRECTIVES["script-src"].append("localhost:5173")
    _CSP_DIRECTIVES["connect-src"].append("localhost:5173")
    _CSP_DIRECTIVES["connect-src"].append("ws://localhost:5173")  # WebSocket for HMR

# Apply the policy based on enforcement mode
# django-csp v4 uses CONTENT_SECURITY_POLICY for enforcement
# and CONTENT_SECURITY_POLICY_REPORT_ONLY for report-only mode
if CSP_ENFORCE:
    CONTENT_SECURITY_POLICY = {"DIRECTIVES": _CSP_DIRECTIVES}
    # No report-only policy when enforcing
    CONTENT_SECURITY_POLICY_REPORT_ONLY = None
else:
    # Report-only mode: violations are logged but not blocked
    CONTENT_SECURITY_POLICY = None
    CONTENT_SECURITY_POLICY_REPORT_ONLY = {"DIRECTIVES": _CSP_DIRECTIVES}
