"""
Django template tags for loading Vite-bundled assets.

In development mode, assets are loaded from the Vite dev server (port 5173).
In production mode, assets are loaded from the manifest file generated by Vite build.

Usage in templates:
    {% load vite %}
    {% vite_asset 'main' %}  <!-- Loads the 'main' entry point -->
    {% vite_hmr %}           <!-- Injects HMR client in dev mode -->
"""

import json
from pathlib import Path

from django import template
from django.conf import settings
from django.templatetags.static import static
from django.utils.safestring import mark_safe

register = template.Library()


def get_vite_manifest():
    """Load and cache the Vite manifest file."""
    manifest_path = Path(settings.STATIC_ROOT) / "dist" / ".vite" / "manifest.json"
    if manifest_path.exists():
        return json.loads(manifest_path.read_text())
    return None


@register.simple_tag
def vite_asset(entry_name):
    """
    Load a Vite asset, handling dev vs prod environments.

    Args:
        entry_name: The entry point name as defined in vite.config.js

    Returns:
        HTML script tag(s) for the entry point and any CSS dependencies.
    """
    if settings.DEBUG and getattr(settings, "VITE_DEV_MODE", True):
        # In dev, load from Vite dev server
        script_url = f"http://localhost:5173/js/vite/{entry_name}.js"
        return mark_safe(f'<script type="module" src="{script_url}"></script>')

    # In production, read from manifest
    manifest = get_vite_manifest()
    if not manifest:
        # Fallback if no manifest exists
        return mark_safe(f"<!-- Vite manifest not found for {entry_name} -->")

    # Find the entry in manifest (format: static/js/vite/main.js -> static/dist/...)
    entry_key = f"static/js/vite/{entry_name}.js"
    if entry_key not in manifest:
        return mark_safe(f"<!-- Vite entry {entry_name} not found in manifest -->")

    entry = manifest[entry_key]
    tags = []

    # Add CSS imports if any
    if "css" in entry:
        for css_file in entry["css"]:
            css_url = static(f"dist/{css_file}")
            tags.append(f'<link rel="stylesheet" href="{css_url}">')

    # Add the main script
    js_url = static(f"dist/{entry['file']}")
    tags.append(f'<script type="module" src="{js_url}"></script>')

    return mark_safe("\n".join(tags))


@register.simple_tag
def vite_hmr():
    """
    Inject the Vite HMR client script in development mode.

    Returns:
        HTML script tag for HMR client in dev mode, empty string in prod.
    """
    if settings.DEBUG and getattr(settings, "VITE_DEV_MODE", True):
        return mark_safe('<script type="module" src="http://localhost:5173/@vite/client"></script>')
    return ""


@register.simple_tag
def vite_react_refresh():
    """
    Inject React Refresh runtime for HMR (if using React).

    Returns:
        HTML script tag for React Refresh in dev mode, empty string in prod.
    """
    if settings.DEBUG and getattr(settings, "VITE_DEV_MODE", True):
        return mark_safe(
            """
<script type="module">
  import RefreshRuntime from 'http://localhost:5173/@react-refresh'
  RefreshRuntime.injectIntoGlobalHook(window)
  window.$RefreshReg$ = () => {}
  window.$RefreshSig$ = () => (type) => type
  window.__vite_plugin_react_preamble_installed__ = true
</script>
"""
        )
    return ""
