# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Recording")

model_instance <- Recording$new()

test_that("id", {
  # tests for the property `id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)
  # Name of the recording

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)
  # Description of the recording

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("location", {
  # tests for the property `location` (character)
  # Location where the recording was made

  # uncomment below to test the property
  #expect_equal(model.instance$`location`, "EXPECTED_RESULT")
})

test_that("recorded_date", {
  # tests for the property `recorded_date` (character)
  # Date when the recording was made

  # uncomment below to test the property
  #expect_equal(model.instance$`recorded_date`, "EXPECTED_RESULT")
})

test_that("duration", {
  # tests for the property `duration` (numeric)
  # Duration of the recording in seconds

  # uncomment below to test the property
  #expect_equal(model.instance$`duration`, "EXPECTED_RESULT")
})

test_that("sample_rate", {
  # tests for the property `sample_rate` (integer)
  # Sample rate of the recording in Hz

  # uncomment below to test the property
  #expect_equal(model.instance$`sample_rate`, "EXPECTED_RESULT")
})

test_that("project", {
  # tests for the property `project` (Project)

  # uncomment below to test the property
  #expect_equal(model.instance$`project`, "EXPECTED_RESULT")
})

test_that("wav_file_url", {
  # tests for the property `wav_file_url` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`wav_file_url`, "EXPECTED_RESULT")
})

test_that("created_at", {
  # tests for the property `created_at` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`created_at`, "EXPECTED_RESULT")
})
