# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test SpeciesApi")

api_instance <- SpeciesApi$new()

test_that("SpeciesCreate", {
  # tests for SpeciesCreate
  # base path: http://localhost
  # ViewSet for managing species.
  # @param species_request SpeciesRequest 
  # @return [Species]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("SpeciesDestroy", {
  # tests for SpeciesDestroy
  # base path: http://localhost
  # ViewSet for managing species.
  # @param id integer A unique integer value identifying this species.
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("SpeciesList", {
  # tests for SpeciesList
  # base path: http://localhost
  # ViewSet for managing species.
  # @param page integer A page number within the paginated result set. (optional)
  # @return [PaginatedSpeciesList]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("SpeciesPartialUpdate", {
  # tests for SpeciesPartialUpdate
  # base path: http://localhost
  # ViewSet for managing species.
  # @param id integer A unique integer value identifying this species.
  # @param patched_species_request PatchedSpeciesRequest  (optional)
  # @return [Species]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("SpeciesRetrieve", {
  # tests for SpeciesRetrieve
  # base path: http://localhost
  # ViewSet for managing species.
  # @param id integer A unique integer value identifying this species.
  # @return [Species]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("SpeciesUpdate", {
  # tests for SpeciesUpdate
  # base path: http://localhost
  # ViewSet for managing species.
  # @param id integer A unique integer value identifying this species.
  # @param species_request SpeciesRequest 
  # @return [Species]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
