# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test TaskRequest")

model_instance <- TaskRequest$new()

test_that("status", {
  # tests for the property `status` (StatusEnum)

  # uncomment below to test the property
  #expect_equal(model.instance$`status`, "EXPECTED_RESULT")
})

test_that("onset", {
  # tests for the property `onset` (numeric)
  # Start time of the segment in seconds

  # uncomment below to test the property
  #expect_equal(model.instance$`onset`, "EXPECTED_RESULT")
})

test_that("offset", {
  # tests for the property `offset` (numeric)
  # End time of the segment in seconds

  # uncomment below to test the property
  #expect_equal(model.instance$`offset`, "EXPECTED_RESULT")
})

test_that("label", {
  # tests for the property `label` (character)
  # Final expert label assigned to this task

  # uncomment below to test the property
  #expect_equal(model.instance$`label`, "EXPECTED_RESULT")
})

test_that("notes", {
  # tests for the property `notes` (character)
  # Additional notes or observations about this task

  # uncomment below to test the property
  #expect_equal(model.instance$`notes`, "EXPECTED_RESULT")
})
