# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ProjectsApi")

api_instance <- ProjectsApi$new()

test_that("ProjectsCreate", {
  # tests for ProjectsCreate
  # base path: http://localhost
  # ViewSet for managing projects.
  # @param project_request ProjectRequest 
  # @return [Project]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ProjectsDestroy", {
  # tests for ProjectsDestroy
  # base path: http://localhost
  # ViewSet for managing projects.
  # @param id integer A unique integer value identifying this project.
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ProjectsList", {
  # tests for ProjectsList
  # base path: http://localhost
  # ViewSet for managing projects.
  # @param page integer A page number within the paginated result set. (optional)
  # @return [PaginatedProjectList]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ProjectsPartialUpdate", {
  # tests for ProjectsPartialUpdate
  # base path: http://localhost
  # ViewSet for managing projects.
  # @param id integer A unique integer value identifying this project.
  # @param patched_project_request PatchedProjectRequest  (optional)
  # @return [Project]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ProjectsRetrieve", {
  # tests for ProjectsRetrieve
  # base path: http://localhost
  # ViewSet for managing projects.
  # @param id integer A unique integer value identifying this project.
  # @return [Project]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ProjectsUpdate", {
  # tests for ProjectsUpdate
  # base path: http://localhost
  # ViewSet for managing projects.
  # @param id integer A unique integer value identifying this project.
  # @param project_request ProjectRequest 
  # @return [Project]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
