# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test PatchedTaskBatchRequest")

model_instance <- PatchedTaskBatchRequest$new()

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("species_id", {
  # tests for the property `species_id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`species_id`, "EXPECTED_RESULT")
})
