# coding: utf-8

"""
    BattyCoda API

    API for BattyCoda - Animal Call Analysis Platform

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.patched_task_batch_request import PatchedTaskBatchRequest

class TestPatchedTaskBatchRequest(unittest.TestCase):
    """PatchedTaskBatchRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PatchedTaskBatchRequest:
        """Test PatchedTaskBatchRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PatchedTaskBatchRequest`
        """
        model = PatchedTaskBatchRequest()
        if include_optional:
            return PatchedTaskBatchRequest(
                name = '0',
                description = '',
                species_id = 56
            )
        else:
            return PatchedTaskBatchRequest(
        )
        """

    def testPatchedTaskBatchRequest(self):
        """Test PatchedTaskBatchRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
