# coding: utf-8

"""
    BattyCoda API

    API for BattyCoda - Animal Call Analysis Platform

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.paginated_recording_list import PaginatedRecordingList

class TestPaginatedRecordingList(unittest.TestCase):
    """PaginatedRecordingList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedRecordingList:
        """Test PaginatedRecordingList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedRecordingList`
        """
        model = PaginatedRecordingList()
        if include_optional:
            return PaginatedRecordingList(
                count = 123,
                next = 'http://api.example.org/accounts/?page=4',
                previous = 'http://api.example.org/accounts/?page=2',
                results = [
                    openapi_client.models.recording.Recording(
                        id = 56, 
                        name = '', 
                        description = '', 
                        location = '', 
                        recorded_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        duration = 1.337, 
                        sample_rate = 56, 
                        project = null, 
                        wav_file_url = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ]
            )
        else:
            return PaginatedRecordingList(
                count = 123,
                results = [
                    openapi_client.models.recording.Recording(
                        id = 56, 
                        name = '', 
                        description = '', 
                        location = '', 
                        recorded_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        duration = 1.337, 
                        sample_rate = 56, 
                        project = null, 
                        wav_file_url = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
        )
        """

    def testPaginatedRecordingList(self):
        """Test PaginatedRecordingList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
