# coding: utf-8

"""
    BattyCoda API

    API for BattyCoda - Animal Call Analysis Platform

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.status_enum import StatusEnum

class TestStatusEnum(unittest.TestCase):
    """StatusEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStatusEnum(self):
        """Test StatusEnum"""
        # inst = StatusEnum()

if __name__ == '__main__':
    unittest.main()
