# coding: utf-8

"""
    BattyCoda API

    API for BattyCoda - Animal Call Analysis Platform

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.recordings_api import RecordingsApi


class TestRecordingsApi(unittest.TestCase):
    """RecordingsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RecordingsApi()

    def tearDown(self) -> None:
        pass

    def test_recordings_create(self) -> None:
        """Test case for recordings_create

        """
        pass

    def test_recordings_destroy(self) -> None:
        """Test case for recordings_destroy

        """
        pass

    def test_recordings_list(self) -> None:
        """Test case for recordings_list

        """
        pass

    def test_recordings_partial_update(self) -> None:
        """Test case for recordings_partial_update

        """
        pass

    def test_recordings_retrieve(self) -> None:
        """Test case for recordings_retrieve

        """
        pass

    def test_recordings_update(self) -> None:
        """Test case for recordings_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
