# coding: utf-8

"""
    BattyCoda API

    API for BattyCoda - Animal Call Analysis Platform

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.recording_request import RecordingRequest

class TestRecordingRequest(unittest.TestCase):
    """RecordingRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RecordingRequest:
        """Test RecordingRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RecordingRequest`
        """
        model = RecordingRequest()
        if include_optional:
            return RecordingRequest(
                name = '0',
                description = '',
                location = '',
                recorded_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                project_id = 56
            )
        else:
            return RecordingRequest(
                name = '0',
        )
        """

    def testRecordingRequest(self):
        """Test RecordingRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
