# coding: utf-8

"""
    BattyCoda API

    API for BattyCoda - Animal Call Analysis Platform

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.tasks_api import TasksApi


class TestTasksApi(unittest.TestCase):
    """TasksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TasksApi()

    def tearDown(self) -> None:
        pass

    def test_tasks_annotate_create(self) -> None:
        """Test case for tasks_annotate_create

        """
        pass

    def test_tasks_list(self) -> None:
        """Test case for tasks_list

        """
        pass

    def test_tasks_retrieve(self) -> None:
        """Test case for tasks_retrieve

        """
        pass


if __name__ == '__main__':
    unittest.main()
