# coding: utf-8

"""
    BattyCoda API

    API for BattyCoda - Animal Call Analysis Platform

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.species_api import SpeciesApi


class TestSpeciesApi(unittest.TestCase):
    """SpeciesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SpeciesApi()

    def tearDown(self) -> None:
        pass

    def test_species_create(self) -> None:
        """Test case for species_create

        """
        pass

    def test_species_destroy(self) -> None:
        """Test case for species_destroy

        """
        pass

    def test_species_list(self) -> None:
        """Test case for species_list

        """
        pass

    def test_species_partial_update(self) -> None:
        """Test case for species_partial_update

        """
        pass

    def test_species_retrieve(self) -> None:
        """Test case for species_retrieve

        """
        pass

    def test_species_update(self) -> None:
        """Test case for species_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
