# coding: utf-8

"""
    BattyCoda API

    API for BattyCoda - Animal Call Analysis Platform

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.recording import Recording

class TestRecording(unittest.TestCase):
    """Recording unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Recording:
        """Test Recording
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Recording`
        """
        model = Recording()
        if include_optional:
            return Recording(
                id = 56,
                name = '',
                description = '',
                location = '',
                recorded_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                duration = 1.337,
                sample_rate = 56,
                project = openapi_client.models.project.Project(
                    id = 56, 
                    name = '', 
                    description = '', 
                    species = null, 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                wav_file_url = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return Recording(
                id = 56,
                name = '',
                duration = 1.337,
                sample_rate = 56,
                project = openapi_client.models.project.Project(
                    id = 56, 
                    name = '', 
                    description = '', 
                    species = null, 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                wav_file_url = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testRecording(self):
        """Test Recording"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
