# coding: utf-8

"""
    BattyCoda API

    API for BattyCoda - Animal Call Analysis Platform

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.patched_species_request import PatchedSpeciesRequest

class TestPatchedSpeciesRequest(unittest.TestCase):
    """PatchedSpeciesRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PatchedSpeciesRequest:
        """Test PatchedSpeciesRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PatchedSpeciesRequest`
        """
        model = PatchedSpeciesRequest()
        if include_optional:
            return PatchedSpeciesRequest(
                name = '0',
                description = ''
            )
        else:
            return PatchedSpeciesRequest(
        )
        """

    def testPatchedSpeciesRequest(self):
        """Test PatchedSpeciesRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
