# coding: utf-8

"""
    BattyCoda API

    API for BattyCoda - Animal Call Analysis Platform

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.species_request import SpeciesRequest

class TestSpeciesRequest(unittest.TestCase):
    """SpeciesRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SpeciesRequest:
        """Test SpeciesRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SpeciesRequest`
        """
        model = SpeciesRequest()
        if include_optional:
            return SpeciesRequest(
                name = '0',
                description = ''
            )
        else:
            return SpeciesRequest(
                name = '0',
        )
        """

    def testSpeciesRequest(self):
        """Test SpeciesRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
