# coding: utf-8

"""
    BattyCoda API

    API for BattyCoda - Animal Call Analysis Platform

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.projects_api import ProjectsApi


class TestProjectsApi(unittest.TestCase):
    """ProjectsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProjectsApi()

    def tearDown(self) -> None:
        pass

    def test_projects_create(self) -> None:
        """Test case for projects_create

        """
        pass

    def test_projects_destroy(self) -> None:
        """Test case for projects_destroy

        """
        pass

    def test_projects_list(self) -> None:
        """Test case for projects_list

        """
        pass

    def test_projects_partial_update(self) -> None:
        """Test case for projects_partial_update

        """
        pass

    def test_projects_retrieve(self) -> None:
        """Test case for projects_retrieve

        """
        pass

    def test_projects_update(self) -> None:
        """Test case for projects_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
