# coding: utf-8

"""
    BattyCoda API

    API for BattyCoda - Animal Call Analysis Platform

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.task_batches_api import TaskBatchesApi


class TestTaskBatchesApi(unittest.TestCase):
    """TaskBatchesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TaskBatchesApi()

    def tearDown(self) -> None:
        pass

    def test_task_batches_create(self) -> None:
        """Test case for task_batches_create

        """
        pass

    def test_task_batches_destroy(self) -> None:
        """Test case for task_batches_destroy

        """
        pass

    def test_task_batches_export_retrieve(self) -> None:
        """Test case for task_batches_export_retrieve

        """
        pass

    def test_task_batches_list(self) -> None:
        """Test case for task_batches_list

        """
        pass

    def test_task_batches_partial_update(self) -> None:
        """Test case for task_batches_partial_update

        """
        pass

    def test_task_batches_retrieve(self) -> None:
        """Test case for task_batches_retrieve

        """
        pass

    def test_task_batches_update(self) -> None:
        """Test case for task_batches_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
